using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace phasmo
{
    internal class GhostData
    {
        private Dictionary<string, string> ghostInfo = new Dictionary<string, string>()
        {
            {"spirit", "Spirits are very common ghosts. They are very powerful, but passive, only attacking when they need to. They defend their place of death to the utmost degree, killing anyone that is caught overstaying their welcome.\r\n\r\nWeakness: A Spirit can be temporarily stopped by burning Smudge Sticks near them." },
            {"wraith", "Wraiths are one of the most dangerous ghosts you will find. It is also the only known ghost that has the ability of flight and has sometimes been known to travel through walls.\r\n\r\nStrength: Wraiths almost never touch the ground, meaning it can't be tracked by footsteps\r\n\r\nWeakness: Wraiths have a toxic reaction to Salt."},
            {"phantom", "A Phantom is a ghost that can possess the living, inducing fear into those around it. They are most commonly summoned from Ouija Boards.\r\n\r\nStrength: Looking at a Phantom will drop your sanity considerably faster.\r\n\r\nWeakness: Taking a photo of the Phantom will make it temporarily disappear."},
            {"poltergeist", "One of the most famous ghosts, the Poltergeist. Known to manipulate objects around it to spread fear into its victims.\r\n\r\nStrength: Poltergeists can throw multiple objects at once, and with great force.\r\n\r\nWeakness: With nothing to throw, Poltergeists become powerless."},
            {"banshee", "The singing siren, known for attracting its victims through song. It has been known to single out its prey before making a killing blow.\r\n\r\nStrength: Banshee's will weaken their target before striking.\r\n\r\nWeakness: Banshee's can sometimes be heard screaming with a parabolic microphone."},
            {"jinn", "A Jinn is a territorial ghost that will attack when threatened. It has also been known to be able to travel at significant speed.\r\n\r\nStrength: A Jinn will travel at a faster speed if its victim is far away.\r\n\r\nWeakness: Turning off the location's power source will prevent the Jinn from using its ability."},
            {"mare", "A Mare is the source of all nightmares, making it most powerful in the dark.\r\n\r\nStrength: A Mare will have an increased chance to attack in the dark.\r\n\r\nWeakness: Turning the lights on around the Mare will lower its chance to attack."},
            {"revenant", "A Revenant is a violent ghost that will attack indiscriminately. Their speed can be deceiving, as they are slow will dormant; however, as soon as they hunt they can move incredibly fast.\r\n\r\nStrength: A Revenant will travel at a significantly faster speed when hunting their prey.\r\n\r\nWeakness: Hiding from the Revenant will cause it to move very slowly."},
            { "shade", "A Shade is known to be very shy. There is evidence to suggest that a Shade will stop all paranomrmal activity if there are multiple people nerby.\r\n\r\nStrength: Shades are much harder to find.\r\n\r\nWeakness: The ghost will not enter a hunt if there are multiple people nearby."},
            {"demon", "Demons are the most aggressive ghosts we've ever encountered. Known to attack without reason, they seem to enjoy the thrill of the hunt.\r\n\r\nStrength: Demons will initiate hunts more often than other ghosts.\r\n\r\nWeakness: Demons fear the Crucifix and will be less aggressive near one."},
            {"yurei", "A Yurei is a ghost that has returned to the physical world, usually for the purpose of revenge or hatred.\r\n\r\nStrength: Yureis have been known to have a stronger effect on people's sanity.\r\n\r\nWeakness: Smudging the Yurei's place of death will trap it temporarily, reducing how much it wanders."},
            {"oni", "Onis love to scare their victims as much as possible before attacking. They are often seen in their physical form, guarding their place of death.\r\n\r\nStrength: Oni are much more active whilst people are nearby and will drain their sanity faster when manifesting.\r\n\r\nWeakness: Oni disappear less often while hunting their prey."},
            {"yokai", "Yokai are common ghosts that are attracted to human voices. They can usually be found haunting family homes.\r\n\r\nStrength: Talking near a Yokai will anger it, increasing the chance of an attack.\r\n\r\nWeakness: When hunting, a Yokai can only hear voices close to it."},
            {"hantu", "A Hantu is a rare ghost that thrives in the coldest climates. The cold seems to make them more aggressive and empowered.\r\n\r\nStrength: Lower temperatures allow the Hantu to move at faster speeds.\r\n\r\nWeakness: Hantus move slower in warmer areas."},
            {"goryo", "When a Goryo passes trough a DOTS projector, using a video camera is the only way to see it.\r\n\r\nStrength: A Goryo will usually only show itself on camera if there are no people nearby.\r\n\r\nWeakness: They are rarely seen far from their place of death."},
            {"myling", "A Myling is a very vocal and active ghost. They are rumoured to be quiet when hunting their prey.\r\n\r\nStrength: A Myling is known to be quieter when hunting.\r\n\r\nWeakness: Mylings more frequently make paranormal sounds."},
            {"onryo", "The Onryo is often referred to as \"The Wrathful Spirit\". It steals souls from dying victims' bodies to seek revenge. This ghost has been known to fear any form of fire, and will do anything to be far from it.\r\n\r\nStrength: Extinguishing a flame can cause an Onryo to attack.\r\n\r\nWeakness: When threatened, this ghost will be less likely to hunt."},
            {"the_twins", "These ghosts have been reported to mimic each other's actions. They alternate their attacks to confuse their prey.\r\n\r\nStrength: Either Twin can be angered and initiate an attack on their prey.\r\n\r\nWeakness: The Twins will often interact with the environment at the same time."},
            {"raiju", "A Raiju is a demon that thrives on electrical current. While generally calm, they can become agitated when overhwlemed with power.\r\n\r\nStrength: A Raiju can siphon power from nearby electrical devices, making it move faster.\r\n\r\nWeakness: Raiju are constantly disrupting electronic equipment when attacking, making it easier to track."},
            {"obake", "Obake are terrifying shape-shifters, capable of taking on many forms. They have been seen taking on humanoid shapes to attract their prey.\r\n\r\nStrength: When interacting with the environment, an Obake will rarely leave a trace.\r\n\r\nWeakness: Sometimes this ghost will shapeshift, leaving behind unique evidence."},
            {"the_mimic", "The Mimic is an elusive, mysterious, copycat ghost that mirrors traits and behaviours from others, including other ghost types.\r\n\r\nStrength: We're unsure what this ghost is capable of. Be careful.\r\n\r\nWeakness: Several reports have noted ghost orb sightings near mimics."},
            {"moroi", "Moroi have risen from the grave to drain energy from the living. They have been known to place curses on their victims, curable only by antidotes or moving very far away.\r\n\r\nStrength: The weaker their victims, the stronger the Moroi becomes.\r\n\r\nWeakness: Moroi suffer from hyperosmia, weakning them for longer periods."},
            {"deogen", "Sometimes surrounded by an endless fog, Deogen have been eluding ghost hunters for years.\r\n\r\nThese ghosts have been reported to find even the most hidden prey, before stalking them into exhaustion.\r\n\r\nStrength: Deogen constantly sense the living. You can run but you can't hide.\r\n\r\nWeakness: Deogen require a lot of energy to form and will move very slowly when approaching its victim."},
            {"thaye", "Thaye have been known to rapidly age over time, even in the afterlife. From what we've learned, they seem to deteriorate faster while within the presence of the living.\r\n\r\nStrength: Upon entering the location, Thaye will become active, defensive and agile.\r\n\r\nWeakness: Thaye will weaken over time, making them weaker, slower and less aggressive"},
        };

        string spirit = "Spirits are very common ghosts. They are very powerful, but passive, only attacking when they need to. They defend their place of death to the utmost degree, killing anyone that is caught overstaying their welcome.\r\n\r\nWeakness: A Spirit can be temporarily stopped by burning Smudge Sticks near them.";
        string wraith = "Wraiths are one of the most dangerous ghosts you will find. It is also the only known ghost that has the ability of flight and has sometimes been known to travel through walls.\r\n\r\nStrength: Wraiths almost never touch the ground, meaning it can't be tracked by footsteps\r\n\r\nWeakness: Wraiths have a toxic reaction to Salt.";
        string phantom = "A Phantom is a ghost that can possess the living, inducing fear into those around it. They are most commonly summoned from Ouija Boards.\r\n\r\nStrength: Looking at a Phantom will drop your sanity considerably faster.\r\n\r\nWeakness: Taking a photo of the Phantom will make it temporarily disappear.";
        string poltergeist = "One of the most famous ghosts, the Poltergeist. Known to manipulate objects around it to spread fear into its victims.\r\n\r\nStrength: Poltergeists can throw multiple objects at once, and with great force.\r\n\r\nWeakness: With nothing to throw, Poltergeists become powerless.";
        string banshee = "The singing siren, known for attracting its victims through song. It has been known to single out its prey before making a killing blow.\r\n\r\nStrength: Banshee's will weaken their target before striking.\r\n\r\nWeakness: Banshee's can sometimes be heard screaming with a parabolic microphone.";
        string jinn = "A Jinn is a territorial ghost that will attack when threatened. It has also been known to be able to travel at significant speed.\r\n\r\nStrength: A Jinn will travel at a faster speed if its victim is far away.\r\n\r\nWeakness: Turning off the location's power source will prevent the Jinn from using its ability.";
        string mare = "A Mare is the source of all nightmares, making it most powerful in the dark.\r\n\r\nStrength: A Mare will have an increased chance to attack in the dark.\r\n\r\nWeakness: Turning the lights on around the Mare will lower its chance to attack.";
        string revenant = "A Revenant is a violent ghost that will attack indiscriminately. Their speed can be deceiving, as they are slow will dormant; however, as soon as they hunt they can move incredibly fast.\r\n\r\nStrength: A Revenant will travel at a significantly faster speed when hunting their prey.\r\n\r\nWeakness: Hiding from the Revenant will cause it to move very slowly.";
        string shade = "A Shade is known to be very shy. There is evidence to suggest that a Shade will stop all paranomrmal activity if there are multiple people nerby.\r\n\r\nStrength: Shades are much harder to find.\r\n\r\nWeakness: The ghost will not enter a hunt if there are multiple people nearby.";
        string demon = "Demons are the most aggressive ghosts we've ever encountered. Known to attack without reason, they seem to enjoy the thrill of the hunt.\r\n\r\nStrength: Demons will initiate hunts more often than other ghosts.\r\n\r\nWeakness: Demons fear the Crucifix and will be less aggressive near one.";
        string yurei = "A Yurei is a ghost that has returned to the physical world, usually for the purpose of revenge or hatred.\r\n\r\nStrength: Yureis have been known to have a stronger effect on people's sanity.\r\n\r\nWeakness: Smudging the Yurei's place of death will trap it temporarily, reducing how much it wanders.";
        string oni = "Onis love to scare their victims as much as possible before attacking. They are often seen in their physical form, guarding their place of death.\r\n\r\nStrength: Oni are much more active whilst people are nearby and will drain their sanity faster when manifesting.\r\n\r\nWeakness: Oni disappear less often while hunting their prey.";
        string yokai = "Yokai are common ghosts that are attracted to human voices. They can usually be found haunting family homes.\r\n\r\nStrength: Talking near a Yokai will anger it, increasing the chance of an attack.\r\n\r\nWeakness: When hunting, a Yokai can only hear voices close to it.";
        string hantu = "A Hantu is a rare ghost that thrives in the coldest climates. The cold seems to make them more aggressive and empowered.\r\n\r\nStrength: Lower temperatures allow the Hantu to move at faster speeds.\r\n\r\nWeakness: Hantus move slower in warmer areas.";
        string goryo = "When a Goryo passes trough a DOTS projector, using a video camera is the only way to see it.\r\n\r\nStrength: A Goryo will usually only show itself on camera if there are no people nearby.\r\n\r\nWeakness: They are rarely seen far from their place of death.";
        string myling = "A Myling is a very vocal and active ghost. They are rumoured to be quiet when hunting their prey.\r\n\r\nStrength: A Myling is known to be quieter when hunting.\r\n\r\nWeakness: Mylings more frequently make paranormal sounds.";
        string onryo = "The Onryo is often referred to as \"The Wrathful Spirit\". It steals souls from dying victims' bodies to seek revenge. This ghost has been known to fear any form of fire, and will do anything to be far from it.\r\n\r\nStrength: Extinguishing a flame can cause an Onryo to attack.\r\n\r\nWeakness: When threatened, this ghost will be less likely to hunt.";
        string the_twins = "These ghosts have been reported to mimic each other's actions. They alternate their attacks to confuse their prey.\r\n\r\nStrength: Either Twin can be angered and initiate an attack on their prey.\r\n\r\nWeakness: The Twins will often interact with the environment at the same time.";
        string raiju = "A Raiju is a demon that thrives on electrical current. While generally calm, they can become agitated when overhwlemed with power.\r\n\r\nStrength: A Raiju can siphon power from nearby electrical devices, making it move faster.\r\n\r\nWeakness: Raiju are constantly disrupting electronic equipment when attacking, making it easier to track.";
        string obake = "Obake are terrifying shape-shifters, capable of taking on many forms. They have been seen taking on humanoid shapes to attract their prey.\r\n\r\nStrength: When interacting with the environment, an Obake will rarely leave a trace.\r\n\r\nWeakness: Sometimes this ghost will shapeshift, leaving behind unique evidence.";
        string the_mimic = "The Mimic is an elusive, mysterious, copycat ghost that mirrors traits and behaviours from others, including other ghost types.\r\n\r\nStrength: We're unsure what this ghost is capable of. Be careful.\r\n\r\nWeakness: Several reports have noted ghost orb sightings near mimics.";
        string moroi = "Moroi have risen from the grave to drain energy from the living. They have been known to place curses on their victims, curable only by antidotes or moving very far away.\r\n\r\nStrength: The weaker their victims, the stronger the Moroi becomes.\r\n\r\nWeakness: Moroi suffer from hyperosmia, weakning them for longer periods.";
        string deogen = "Sometimes surrounded by an endless fog, Deogen have been eluding ghost hunters for years.\r\n\r\nThese ghosts have been reported to find even the most hidden prey, before stalking them into exhaustion.\r\n\r\nStrength: Deogen constantly sense the living. You can run but you can't hide.\r\n\r\nWeakness: Deogen require a lot of energy to form and will move very slowly when approaching its victim.";
        string thaye = "Thaye have been known to rapidly age over time, even in the afterlife. From what we've learned, they seem to deteriorate faster while within the presence of the living.\r\n\r\nStrength: Upon entering the location, Thaye will become active, defensive and agile.\r\n\r\nWeakness: Thaye will weaken over time, making them weaker, slower and less aggressive";

        public Dictionary<string, string> GhostInfo { get => ghostInfo; set => ghostInfo = value; }
    }
}
